### ISSUE TITLE
Tweak disclaimer langauge

### ISSUE THREAD

**Issue by cjdd3b** [striblab/campfi-2018#18]
- [x] Add 2017-2018 cycle note to Senate
- [x] Need to footnote Pawlenty in gov's race?
- [x] Pass through language that's in there already

**Comment by cjdd3b** [comment]
Will do Saturday/Sunday

**Comment by cjsinner** [comment]
re: pawlenty, I took it out because it's likely he will file a report now
that he's officially in the race. not positive on that, however.

**Comment by cjdd3b** [comment]
Small tweak, per: https://github.com/striblab/campfi-2018/commit/4be69a5cd7ef9eb30c992568e9e1da95391807c9

We can decide on Pawlenty if he has money to file – which he very well might not. If not, we should figure out a way to call him out anyway, possibly in a footnote.
